### ISSUE TITLE
WebMap with .csv published from Google Sheets

### ISSUE THREAD

**Issue by igrasshoff** [Esri/map-tour-storytelling-template-js#53]
I am trying to leverage a web map that includes a "Map Tour" data layer published as .csv from Google Sheets.  When the app loads I get the message, "An error has occurred. The web map does not contain a valid data layer for Map Tour."

I am able to utilize .csv published from Google Sheets via the ArcGIS Online hosted version of the map tour template, just not the developer edition.  Also, I tested and I am able to consume a web map with "embedded" .csv, aka when setting up the web map -> add -> Layer From File.  If I add the .csv this way everything works in the developer edition.

**Comment by glazou** [comment]
In the network inspector, do you see a request sent to get the csv? It may be a protocol issue like Google that only return the CSV if you app is over HTTPS. Depending on your ArcGIS Online setting, you may be able to load the application over HTTP and HTTPS to see if you see a difference.

If that doesn't help, if you can share the webmap or a dummy CSV, I can take a look, that may be a bug.

**Comment by amandaly** [comment]
Hey Glazou, I was having this issue so I moved my Story Map over to a secure server but I am still getting the same error. Here is the link, if you could take a look and see what I might be doing wrong.   https://secure.www.upenn.edu/business-services/arboretum/tours_sculpture_map.html

TIA

**Comment by glazou** [comment]
Hey,

Because Google Docs does not allow request from another server to access directly that content, you will need to configure a proxy on your server. Esri provide proxy for multiple server at https://github.com/Esri/resource-proxy . Once deployed, you need to configure it in the file `app/maptour-config.js`, at the very bottom. 

Note that some other services like GitHub do not require you to set up a proxy and that is usually a simpler option. If you go that route, you will still need to add the following code in `index.html` to instruct the app to not use the proxy for that server. For example, for GitHub it is

```
require(["esri/config"], function(esriConfig) {
  esriConfig.defaults.io.corsEnabledServers.push("raw.githubusercontent.com");
});
```

To be added before this line https://github.com/Esri/map-tour-storytelling-template-js/blob/master/MapTour/src/index.html#L1260

![image](https://cloud.githubusercontent.com/assets/994078/18326987/19c599e6-74fd-11e6-9970-4f2a2119eadb.png)

**Comment by amandaly** [comment]
Hey I tried using Github like you suggested because I'm not sure about adding the proxy to the server since I access the server using SFTP and don't have direct access to it. Here's my Github page for it: https://amandaly.github.io/tours/tours_native_trees_map.html

I added the workaround to not use the proxy and to point to Github but I'm getting the same error. Thank you for your help again!

**Comment by glazou** [comment]
Hey, cool you are almost there. 
Now you also need to:
- host your CSV data on GitHub
- modify the webmap: remove link to Google docs and add link to CSV GitHub on GitHub, the URL need to start with raw.githubusercontent (usually just click on the raw button in the UI)

**Comment by imclean557** [comment]
Was this resolved for anyone?  I'm having a similar issue. A CMS provides the CSV output, currently only 5 points for testing.

**Test 1**

1. Download CSV file (same URL as in Test 2)
2. Add Layer from File: Import CSV file
3. Save map
4. Reference map from self-hosted Map Tour 
5. Success!

**Test 2*

1. Add Layer from Web: CSV URL
2. Save map
3. Reference map from self-hosted Map Tour 
4. "An error has occurred. The web map does not contain a valid data layer for Map Tour."

The proxy was an issue so I removed it as per the instructions above.  Watching the Network tab in Developer Tools I can see the CSV is sucked down properly, still I receive the error.

With Test 1, I noticed the data URL returns JSON from ArcGIS, while in test 2 it grabs the CSV file directly. Can the self-hosted option handle both CSV and JSON data?

**Comment by oevans** [comment]
By any chance is your app deployed using a path that contains `/app/` or `/home/`? There is a known issue with using those folder names in the app path.

**Comment by imclean557** [comment]
The path is `/67stories/ ` which is where `index.html` resides. The subdirectories are the ones which are part of the app: `app`, `resources` and `samples`.

**Comment by imclean557** [comment]
I've also tried `/brnstories/` to rule out starting with a number.

**Comment by imclean557** [comment]
I've resolved our problem. In my case, the column names weren't precise enough.  Online documentation within the map builder, such as the downloadable `locations.csv` example,  suggested certain names, such as "description", while other documentation suggested "Caption":

http://ugis.esri.com/downloads/Map%20Tour%20Attributes%20Matrix.pdf
http://ugis.esri.com/downloads/StorytellingMapTour_Doc.pdf

"Icon_color" needed to be exact for the self-hosted version. The hosted version was a bit more lenient.

**Comment by oevans** [comment]
Great to hear you've resolved this. We'll look to incorporate your feedback in a future release.
